MovieLens AI — End-to-End Movie Intelligence & Recommendation System

In [146]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings 

warnings.filterwarnings('ignore')

In [147]:
df = pd.read_csv('imdb-movies-dataset.csv.zip')

In [148]:
df.head()

,Poster,Title,Year,Certificate,Duration (min),Genre,Rating,Metascore,Director,Cast,Votes,Description,Review Count,Review Title,Review
0,https://m.media-amazon.com/images/M/MV5BYWRkZj...,The Idea of You,2023.0,R,115.0,"Comedy, Drama, Romance",6.4,67.0,Michael Showalter,"Anne Hathaway, Nicholas Galitzine, Ella Rubin,...","28,744","Solène, a 40-year-old single mom, begins an un...",166,Hypocrisy as an idea,"This film, as well as the reaction to it, is a..."
1,https://m.media-amazon.com/images/M/MV5BZGI4NT...,Kingdom of the Planet of the Apes,2023.0,PG-13,145.0,"Action, Adventure, Sci-Fi",7.3,66.0,Wes Ball,"Owen Teague, Freya Allan, Kevin Durand, Peter ...","22,248","Many years after the reign of Caesar, a young ...",183,A phenomenal start to another trilogy!,"I'm a big fan of all the planet of the apes, a..."
2,https://m.media-amazon.com/images/M/MV5BZjIyOT...,Unfrosted,2023.0,PG-13,97.0,"Biography, Comedy, History",5.5,42.0,Jerry Seinfeld,"Isaac Bae, Jerry Seinfeld, Chris Rickett, Rach...","18,401","In 1963 Michigan, business rivals Kellogg's an...",333,not funny,Pretty much the worst criticism you can lay on...
3,https://m.media-amazon.com/images/M/MV5BMjA5Zj...,The Fall Guy,2023.0,PG-13,126.0,"Action, Comedy, Drama",7.3,73.0,David Leitch,"Ryan Gosling, Emily Blunt, Aaron Taylor-Johnso...","38,953",A down-and-out stuntman must find the missing ...,384,Everything you needed and more!,Just got out of the Austin premier at SXSW and...
4,https://m.media-amazon.com/images/M/MV5BNTk1MT...,Challengers,2023.0,R,131.0,"Drama, Romance, Sport",7.7,82.0,Luca Guadagnino,"Zendaya, Mike Faist, Josh O'Connor, Darnell Ap...","32,517","Tashi, a former tennis prodigy turned coach, t...",194,"Watch ""Match Point"" instead",This is a tough one. I liked the concept and t...

In [149]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Poster          10000 non-null  str
 1   Title           10000 non-null  str
 2   Year            9850 non-null   float64
 3   Certificate     7370 non-null   str
 4   Duration (min)  9664 non-null   float64
 5   Genre           9993 non-null   str
 6   Rating          9596 non-null   float64
 7   Metascore       7555 non-null   float64
 8   Director        9995 non-null   str
 9   Cast            9961 non-null   str
 10  Votes           9596 non-null   str
 11  Description     10000 non-null  str
 12  Review Count    9999 non-null   str
 13  Review Title    9483 non-null   str
 14  Review          9484 non-null   str
dtypes: float64(4), str(11)
memory usage: 19.9 MB

In [150]:
df.columns

Index(['Poster', 'Title', 'Year', 'Certificate', 'Duration (min)', 'Genre',
       'Rating', 'Metascore', 'Director', 'Cast', 'Votes', 'Description',
       'Review Count', 'Review Title', 'Review'],
      dtype='str')

In [151]:
df.shape

(10000, 15)

In [152]:
df.isnull().sum()

Poster               0
Title                0
Year               150
Certificate       2630
Duration (min)     336
Genre                7
Rating             404
Metascore         2445
Director             5
Cast                39
Votes              404
Description          0
Review Count         1
Review Title       517
Review             516
dtype: int64

In [153]:
df['Votes'] = df['Votes'].str.replace(",", '')
df['Votes'] = pd.to_numeric(df['Votes'], errors='coerce')

In [154]:
df = df.dropna(subset= ['Rating'])

In [155]:
df['Rating'].isnull().sum()

np.int64(0)

In [156]:
df['Year'] = df['Year'].fillna(df['Year'].median())
df['Duration (min)'] = df['Duration (min)'].fillna(df['Duration (min)'].median())

In [157]:
df[['Year', 'Duration (min)']].isnull().sum()

Year              0
Duration (min)    0
dtype: int64

In [158]:
df = df.drop(columns = ['Metascore'])

In [159]:
df.shape

(9596, 14)

In [160]:
df = df.dropna(subset = ['Genre'])

In [161]:
df = df.dropna(subset= ['Director'])
df = df.drop(columns= ['Certificate'])

In [162]:
df.shape

(9596, 13)

In [163]:
df['Genre'].value_counts().head(20)

Genre
Drama                           483
Comedy, Drama, Romance          366
Drama, Romance                  355
Comedy, Drama                   289
Comedy                          283
Comedy, Romance                 236
Action, Crime, Drama            231
Animation, Adventure, Comedy    205
Action, Adventure, Comedy       184
Crime, Drama, Mystery           176
Horror, Mystery, Thriller       164
Crime, Drama, Thriller          163
Horror, Thriller                158
Action, Crime, Thriller         158
Horror                          148
Action, Adventure, Sci-Fi       146
Action, Adventure, Drama        143
Action, Comedy, Crime           136
Drama, Thriller                 128
Biography, Drama, History       121
Name: count, dtype: int64

In [164]:
genres = df['Genre'].str.split(', ').explode()
genres_count = genres.value_counts()
genres_count

Genre
Drama          5173
Comedy         3159
Action         2328
Thriller       1736
Adventure      1687
Crime          1687
Romance        1567
Horror         1446
Mystery        1055
Sci-Fi          749
Fantasy         716
Biography       636
Family          459
Animation       443
History         321
Music           250
Sport           199
War             196
Western         141
Documentary     119
Musical         116
Film-Noir        37
Name: count, dtype: int64

In [165]:
df[['Title', 'Year', 'Duration (min)', 'Genre', 'Rating', 'Director']].head()

,Title,Year,Duration (min),Genre,Rating,Director
0,The Idea of You,2023.0,115.0,"Comedy, Drama, Romance",6.4,Michael Showalter
1,Kingdom of the Planet of the Apes,2023.0,145.0,"Action, Adventure, Sci-Fi",7.3,Wes Ball
2,Unfrosted,2023.0,97.0,"Biography, Comedy, History",5.5,Jerry Seinfeld
3,The Fall Guy,2023.0,126.0,"Action, Comedy, Drama",7.3,David Leitch
4,Challengers,2023.0,131.0,"Drama, Romance, Sport",7.7,Luca Guadagnino

In [166]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:1234@localhost:5432/movielens_ai"
)

print("Database connected!")

Database connected!

In [167]:
movies_df = df[
    ['Title', 'Year', 'Duration (min)', 'Genre', 'Rating', 'Director', 'Votes']
].copy()

movies_df.columns = [
    'title',
    'year',
    'duration',
    'genre',
    'rating',
    'director',
    'votes'
]

movies_df.head()

,title,year,duration,genre,rating,director,votes
0,The Idea of You,2023.0,115.0,"Comedy, Drama, Romance",6.4,Michael Showalter,28744.0
1,Kingdom of the Planet of the Apes,2023.0,145.0,"Action, Adventure, Sci-Fi",7.3,Wes Ball,22248.0
2,Unfrosted,2023.0,97.0,"Biography, Comedy, History",5.5,Jerry Seinfeld,18401.0
3,The Fall Guy,2023.0,126.0,"Action, Comedy, Drama",7.3,David Leitch,38953.0
4,Challengers,2023.0,131.0,"Drama, Romance, Sport",7.7,Luca Guadagnino,32517.0

In [168]:
movies_df.to_sql(
    'movies',
    engine,
    if_exists='append',
    index=False
)

print("Movies inserted successfully!")

Movies inserted successfully!

In [169]:
result = pd.read_sql(
    "SELECT COUNT(*) AS total_movies FROM movies",
    engine
)

result

   total_movies
0         38384

In [170]:
from sqlalchemy import text

with engine.connect() as connection:
    results = pd.read_sql_query(text(query), connection)

results

TypeError: expected string or bytes-like object, got 'TextClause'

In [ ]:
with engine.connect() as connection:
    duplicates = pd.read_sql_query(
        text("""
            SELECT title, COUNT(*) AS count
            FROM movies
            GROUP BY title
            HAVING COUNT(*) > 1
            ORDER BY count DESC;
        """),
        connection
    )

duplicates.head(20)

                   title  count
0         A Star Is Born      8
1   The Three Musketeers      8
2              The Mummy      8
3        The Jungle Book      6
4                 Scream      6
5           Black Beauty      6
6             Robin Hood      6
7             Cinderella      6
8              Halloween      6
9     The Little Mermaid      6
10             King Kong      6
11          Mother's Day      6
12               Shut In      6
13                 Shaft      6
14  Beauty and the Beast      6
15               Dracula      6
16       Black Christmas      6
17               The Kid      6
18              Fortress      6
19            Dirty Work      4

In [ ]:
with engine.connect() as connection:
    check = pd.read_sql_query(
        text("""
            SELECT *
            FROM movies
            WHERE title = 'Psycho';
        """),
        connection
    )

check

,id,title,year,duration,genre,rating,director,votes
0,576,Psycho,2024,109,"Horror, Mystery, Thriller",8.5,Alfred Hitchcock,719582
1,5284,Psycho,2016,105,"Horror, Mystery, Thriller",4.6,Gus Van Sant,50746
2,10172,Psycho,2024,109,"Horror, Mystery, Thriller",8.5,Alfred Hitchcock,719582
3,14880,Psycho,2016,105,"Horror, Mystery, Thriller",4.6,Gus Van Sant,50746

In [ ]:
movies_df = movies_df.drop_duplicates()

In [ ]:
movies_df.shape

(9596, 7)

In [ ]:
movies_df.duplicated().sum()

np.int64(0)

In [ ]:
from sqlalchemy import text

with engine.begin() as connection:
    connection.execute(text("TRUNCATE TABLE movies RESTART IDENTITY"))

movies_df.to_sql(
    'movies',
    engine,
    if_exists='append',
    index=False
)

print("Clean data inserted!")

Clean data inserted!

In [ ]:
with engine.connect() as connection:
    result = pd.read_sql_query(
        text("SELECT COUNT(*) AS total_movies FROM movies"),
        connection
    )

result

   total_movies
0          9596

In [ ]:
genre = "Thriller"
min_rating = 7.5
max_runtime = 150
release_year = 2015

query = text("""
    SELECT title, year, duration, genre, rating, director
    FROM movies
    WHERE genre LIKE :genre
      AND rating >= :min_rating
      AND duration <= :max_runtime
      AND year >= :release_year
    ORDER BY rating DESC
    LIMIT 10
""")

with engine.connect() as connection:
    results = pd.read_sql_query(
        query,
        connection,
        params={
            "genre": f"%{genre}%",
            "min_rating": min_rating,
            "max_runtime": max_runtime,
            "release_year": release_year
        }
    )

results

,title,year,duration,genre,rating,director
0,Psycho,2024,109,"Horror, Mystery, Thriller",8.5,Alfred Hitchcock
1,Memento,2024,113,"Mystery, Thriller",8.4,Christopher Nolan
2,The Lives of Others,2016,137,"Drama, Mystery, Thriller",8.4,Florian Henckel von Donnersmarck
3,Vertigo,2016,128,"Mystery, Romance, Thriller",8.3,Alfred Hitchcock
4,M - Eine Stadt sucht einen Mörder,2020,117,"Crime, Mystery, Thriller",8.3,Fritz Lang
5,Kill Bill: Vol. 1,2022,111,"Action, Crime, Thriller",8.2,Quentin Tarantino
6,Shutter Island,2023,138,"Drama, Mystery, Thriller",8.2,Martin Scorsese
7,Yôjinbô,2023,110,"Action, Drama, Thriller",8.2,Akira Kurosawa
8,Jaws,2024,124,"Adventure, Mystery, Thriller",8.1,Steven Spielberg
9,Room,2016,118,"Drama, Thriller",8.1,Lenny Abrahamson

In [ ]:
genres = pd.read_sql_query(
    text("SELECT DISTINCT genre FROM movies"),
    engine
)

genres

                          genre
0           Crime, Drama, Music
1        Comedy, Drama, Western
2       Action, Comedy, Fantasy
3        Comedy, Drama, Musical
4          Crime, Drama, Horror
..                          ...
461    Animation, Drama, Family
462   Fantasy, Horror, Thriller
463          Adventure, Fantasy
464  Documentary, Comedy, Drama
465    Biography, Drama, Horror

[466 rows x 1 columns]