PhishSense AI

In [104]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')

In [105]:
df = pd.read_csv('CEAS_08.csv')

In [106]:
df.head()

,sender,receiver,date,subject,body,label,urls
0,Young Esposito <Young@iworld.de>,user4@gvc.ceas-challenge.cc,"Tue, 05 Aug 2008 16:31:02 -0700",Never agree to be a loser,"Buck up, your troubles caused by small dimensi...",1,1
1,Mok <ipline's1983@icable.ph>,user2.2@gvc.ceas-challenge.cc,"Tue, 05 Aug 2008 18:31:03 -0500",Befriend Jenna Jameson,\nUpgrade your sex and pleasures with these te...,1,1
2,Daily Top 10 <Karmandeep-opengevl@universalnet...,user2.9@gvc.ceas-challenge.cc,"Tue, 05 Aug 2008 20:28:00 -1200",CNN.com Daily Top 10,>+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+...,1,1
3,Michael Parker <ivqrnai@pobox.com>,SpamAssassin Dev <xrh@spamassassin.apache.org>,"Tue, 05 Aug 2008 17:31:20 -0600",Re: svn commit: r619753 - in /spamassassin/tru...,Would anyone object to removing .so from this ...,0,1
4,Gretchen Suggs <externalsep1@loanofficertool.com>,user2.2@gvc.ceas-challenge.cc,"Tue, 05 Aug 2008 19:31:21 -0400",SpecialPricesPharmMoreinfo,\nWelcomeFastShippingCustomerSupport\nhttp://7...,1,1

In [107]:
df.shape

(39154, 7)

In [108]:
df.columns

Index(['sender', 'receiver', 'date', 'subject', 'body', 'label', 'urls'], dtype='str')

In [109]:
df.isnull().sum()

sender        0
receiver    462
date          0
subject      28
body          0
label         0
urls          0
dtype: int64

In [110]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 39154 entries, 0 to 39153
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   sender    39154 non-null  str
 1   receiver  38692 non-null  str
 2   date      39154 non-null  str
 3   subject   39126 non-null  str
 4   body      39154 non-null  str
 5   label     39154 non-null  int64
 6   urls      39154 non-null  int64
dtypes: int64(2), str(5)
memory usage: 66.3 MB

In [111]:
df.drop(columns= ['sender', 'receiver','date'], inplace= True)

In [112]:
df.shape

(39154, 4)

In [113]:
df['subject'] = df['subject'].fillna('')

In [114]:
df.isnull().sum()

subject    0
body       0
label      0
urls       0
dtype: int64

In [115]:
df['label'].value_counts()

label
1    21842
0    17312
Name: count, dtype: int64

In [116]:
df.groupby('label')['body'].count()

label
0    17312
1    21842
Name: body, dtype: int64

In [117]:
df.duplicated().sum()

np.int64(0)

In [118]:
df['text'] = df['subject'] + ' '+ df['body']

In [119]:
df.drop(columns=['body', 'subject'], inplace= True)

In [120]:
df.head()

   label  urls                                               text
0      1     1  Never agree to be a loser Buck up, your troubl...
1      1     1  Befriend Jenna Jameson \nUpgrade your sex and ...
2      1     1  CNN.com Daily Top 10 >+=+=+=+=+=+=+=+=+=+=+=+=...
3      0     1  Re: svn commit: r619753 - in /spamassassin/tru...
4      1     1  SpecialPricesPharmMoreinfo \nWelcomeFastShippi...

In [121]:
df['text'] = df['text'].apply(lambda x : x.lower())

In [122]:
import string 

def remove_punc(txt):
    return txt.translate(str.maketrans('', '',string.punctuation))

In [123]:
df['text'] = df['text'].apply(remove_punc)

In [124]:
import re

def urls(txt):
    return re.sub(r'http\S+|www\S+', '',txt)

In [125]:
df['text'] = df['text'].apply(urls)

In [126]:
def html(txt):
    return re.sub(r'<.*?>','',txt)

In [127]:
df['text'] = df['text'].apply(html)

In [128]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [129]:
stop_w = set(stopwords.words('english'))

In [132]:
def remove_sw(txt):
    words = word_tokenize(str(txt), preserve_line=True)
    cleaned = []

    for i in words:
        if i not in stop_w:
            cleaned.append(i)

    return ' '.join(cleaned)

In [133]:
df['text'] = df['text'].apply(remove_sw)

In [134]:
df

       label  urls                                               text
0          1     1  never agree loser buck troubles caused small d...
1          1     1  befriend jenna jameson upgrade sex pleasures t...
2          1     1  cnncom daily top 10 daily top 10 cnncom top vi...
3          0     1  svn commit r619753 spamassassintrunk libmailsp...
4          1     1  specialpricespharmmoreinfo welcomefastshipping...
...      ...   ...                                                ...
39149      1     0  cnn alerts custom alert cnn alerts custom aler...
39150      1     0  cnn alerts custom alert cnn alerts custom aler...
39151      0     0  slideshow viewer hello great work slide show v...
39152      0     0  note 2digit years mail sender coming intuitcom...
39153      0     1  pythondev pep 370 heads dear fellow pythonista...

[39154 rows x 3 columns]

In [137]:
df.drop(columns= ['urls'], inplace = True)

In [138]:
df.head()

   label                                               text
0      1  never agree loser buck troubles caused small d...
1      1  befriend jenna jameson upgrade sex pleasures t...
2      1  cnncom daily top 10 daily top 10 cnncom top vi...
3      0  svn commit r619753 spamassassintrunk libmailsp...
4      1  specialpricespharmmoreinfo welcomefastshipping...

In [139]:
X = df['text']
y = df['label']

In [140]:
from sklearn.model_selection import train_test_split

In [141]:
X_train, X_test, y_train, y_test= train_test_split(
    X,y,
    random_state= 42,
    test_size= 0.2
)

In [142]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [145]:
tfidf = TfidfVectorizer()
X_train_tf=tfidf.fit_transform(X_train)
X_test_tf= tfidf.transform(X_test)