PhishSense AI

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('CEAS_08.csv')

In [3]:
df.head()

,sender,receiver,date,subject,body,label,urls
0,Young Esposito <Young@iworld.de>,user4@gvc.ceas-challenge.cc,"Tue, 05 Aug 2008 16:31:02 -0700",Never agree to be a loser,"Buck up, your troubles caused by small dimensi...",1,1
1,Mok <ipline's1983@icable.ph>,user2.2@gvc.ceas-challenge.cc,"Tue, 05 Aug 2008 18:31:03 -0500",Befriend Jenna Jameson,\nUpgrade your sex and pleasures with these te...,1,1
2,Daily Top 10 <Karmandeep-opengevl@universalnet...,user2.9@gvc.ceas-challenge.cc,"Tue, 05 Aug 2008 20:28:00 -1200",CNN.com Daily Top 10,>+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+...,1,1
3,Michael Parker <ivqrnai@pobox.com>,SpamAssassin Dev <xrh@spamassassin.apache.org>,"Tue, 05 Aug 2008 17:31:20 -0600",Re: svn commit: r619753 - in /spamassassin/tru...,Would anyone object to removing .so from this ...,0,1
4,Gretchen Suggs <externalsep1@loanofficertool.com>,user2.2@gvc.ceas-challenge.cc,"Tue, 05 Aug 2008 19:31:21 -0400",SpecialPricesPharmMoreinfo,\nWelcomeFastShippingCustomerSupport\nhttp://7...,1,1

In [4]:
df.shape

(39154, 7)

In [5]:
df.columns

Index(['sender', 'receiver', 'date', 'subject', 'body', 'label', 'urls'], dtype='str')

In [6]:
df.isnull().sum()

sender        0
receiver    462
date          0
subject      28
body          0
label         0
urls          0
dtype: int64

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 39154 entries, 0 to 39153
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   sender    39154 non-null  str
 1   receiver  38692 non-null  str
 2   date      39154 non-null  str
 3   subject   39126 non-null  str
 4   body      39154 non-null  str
 5   label     39154 non-null  int64
 6   urls      39154 non-null  int64
dtypes: int64(2), str(5)
memory usage: 66.3 MB

In [8]:
df.drop(columns= ['sender', 'receiver','date'], inplace= True)

In [9]:
df.shape

(39154, 4)

In [10]:
df['subject'] = df['subject'].fillna('')

In [11]:
df.isnull().sum()

subject    0
body       0
label      0
urls       0
dtype: int64

In [12]:
df['label'].value_counts()

label
1    21842
0    17312
Name: count, dtype: int64

In [13]:
df.groupby('label')['body'].count()

label
0    17312
1    21842
Name: body, dtype: int64

In [14]:
df.duplicated().sum()

np.int64(0)

In [16]:
df['text'] = df['subject'] + ' '+ df['body']

In [19]:
df.drop(columns=['body', 'subject'], inplace= True)

In [20]:
df.head()

   label  urls                                               text
0      1     1  Never agree to be a loser Buck up, your troubl...
1      1     1  Befriend Jenna Jameson \nUpgrade your sex and ...
2      1     1  CNN.com Daily Top 10 >+=+=+=+=+=+=+=+=+=+=+=+=...
3      0     1  Re: svn commit: r619753 - in /spamassassin/tru...
4      1     1  SpecialPricesPharmMoreinfo \nWelcomeFastShippi...

In [21]:
df['text'] = df['text'].apply(lambda x : x.lower())

In [24]:
import string 

def remove_punc(txt):
    return txt.translate(str.maketrans('', '',string.punctuation))

In [25]:
df['text'] = df['text'].apply(remove_punc)

In [27]:
import re

def urls(txt):
    return re.sub(r'http\S+|www\S+', '',txt)

In [28]:
df['text'] = df['text'].apply(urls)

In [29]:
def html(txt):
    return re.sub(r'<.*?>','',txt)

In [30]:
df['text'] = df['text'].apply(html)