AI Complaint Intelligence System

In [47]:
import pandas as pd
import numpy as np
import warnings 

warnings.filterwarnings('ignore')

In [48]:
df = pd.read_csv('complaints_processed.csv')

In [49]:
df.drop(columns=['Unnamed: 0'], inplace=True)

In [50]:
df.head()

            product                                          narrative
0       credit_card  purchase order day shipping amount receive pro...
1       credit_card  forwarded message date tue subject please inve...
2    retail_banking  forwarded message cc sent friday pdt subject f...
3  credit_reporting  payment history missing credit report speciali...
4  credit_reporting  payment history missing credit report made mis...

In [51]:
df['product'].value_counts()

product
credit_reporting       91179
debt_collection        23150
mortgages_and_loans    18990
credit_card            15566
retail_banking         13536
Name: count, dtype: int64

In [52]:
df.isnull().sum()

product       0
narrative    10
dtype: int64

In [53]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 162421 entries, 0 to 162420
Data columns (total 2 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   product    162421 non-null  str
 1   narrative  162411 non-null  str
dtypes: str(2)
memory usage: 96.1 MB

In [54]:
df.dropna(subset=['narrative'], inplace=True)

In [55]:
df.isnull().sum()

product      0
narrative    0
dtype: int64

In [56]:
df.duplicated().sum()

np.int64(37735)

In [57]:
df.drop_duplicates(inplace= True)

In [58]:
df.shape

(124676, 2)

In [59]:
df.duplicated().sum()

np.int64(0)

In [60]:
df.head(10)

            product                                          narrative
0       credit_card  purchase order day shipping amount receive pro...
1       credit_card  forwarded message date tue subject please inve...
2    retail_banking  forwarded message cc sent friday pdt subject f...
3  credit_reporting  payment history missing credit report speciali...
4  credit_reporting  payment history missing credit report made mis...
5  credit_reporting  payment history missing credit report made mis...
6  credit_reporting  va date complaint experian credit bureau invol...
7  credit_reporting  account reported abbreviated name full name se...
8  credit_reporting  account reported abbreviated name full name se...
9  credit_reporting  usdoexxxx account reported abbreviated name fu...

In [61]:
df = df[df['narrative'].str.len() >= 10]

In [62]:
df.shape

(124633, 2)

Text Cleaning

Lower Case

In [65]:
df['narrative'] = df['narrative'].apply(lambda x : x.lower())

remove Punctuations