AI Complaint Intelligence System

In [47]:
import pandas as pd
import numpy as np
import warnings 

warnings.filterwarnings('ignore')

In [48]:
df = pd.read_csv('complaints_processed.csv')

In [49]:
df.drop(columns=['Unnamed: 0'], inplace=True)

In [50]:
df.head()

            product                                          narrative
0       credit_card  purchase order day shipping amount receive pro...
1       credit_card  forwarded message date tue subject please inve...
2    retail_banking  forwarded message cc sent friday pdt subject f...
3  credit_reporting  payment history missing credit report speciali...
4  credit_reporting  payment history missing credit report made mis...

In [51]:
df['product'].value_counts()

product
credit_reporting       91179
debt_collection        23150
mortgages_and_loans    18990
credit_card            15566
retail_banking         13536
Name: count, dtype: int64

In [52]:
df.isnull().sum()

product       0
narrative    10
dtype: int64

In [53]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 162421 entries, 0 to 162420
Data columns (total 2 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   product    162421 non-null  str
 1   narrative  162411 non-null  str
dtypes: str(2)
memory usage: 96.1 MB

In [54]:
df.dropna(subset=['narrative'], inplace=True)

In [55]:
df.isnull().sum()

product      0
narrative    0
dtype: int64

In [56]:
df.duplicated().sum()

np.int64(37735)

In [57]:
df.drop_duplicates(inplace= True)

In [58]:
df.shape

(124676, 2)

In [59]:
df.duplicated().sum()

np.int64(0)

In [60]:
df.head(10)

            product                                          narrative
0       credit_card  purchase order day shipping amount receive pro...
1       credit_card  forwarded message date tue subject please inve...
2    retail_banking  forwarded message cc sent friday pdt subject f...
3  credit_reporting  payment history missing credit report speciali...
4  credit_reporting  payment history missing credit report made mis...
5  credit_reporting  payment history missing credit report made mis...
6  credit_reporting  va date complaint experian credit bureau invol...
7  credit_reporting  account reported abbreviated name full name se...
8  credit_reporting  account reported abbreviated name full name se...
9  credit_reporting  usdoexxxx account reported abbreviated name fu...

In [61]:
df = df[df['narrative'].str.len() >= 10]

In [62]:
df.shape

(124633, 2)

Text Cleaning

Lower Case

In [65]:
df['narrative'] = df['narrative'].apply(lambda x : x.lower())

remove Punctuations

In [66]:
import string

def remove_punc(txt) : 
    return txt.translate(str.maketrans('', '', string.punctuation))

In [ ]:
df['narrative'] = df['narrative'].apply(remove_punc)

Remove URL & Links

In [69]:
import re

def remove_url(txt):
    return re.sub(r'http\S+|www\S+', '',txt)

df['narrative'] = df['narrative'].apply(remove_url)

remove HTML tags

In [ ]:
import re 

def remove_html(txt):
    return  re.sub(r'<.*?>', '', txt)

In [72]:
df['narrative'] = df['narrative'].apply(remove_html)

remove emoji

In [73]:
def remove_emoji(txt):
    new = ''
    for i in txt:
        if i.isascii():
            new += i

    return new

df['narrative'] = df['narrative'].apply(remove_emoji)

Remove Stop words

In [74]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [75]:
stop_words = set(stopwords.words('english'))

In [76]:
def remove(txt):
    words = word_tokenize(txt)
    cleaned = []
    for i in words:
        if not i in stop_words:
            cleaned.append(i)

    return ' '.join(cleaned)

In [77]:
df['narrative'] = df['narrative'].apply(remove)

In [78]:
df.loc[1]['narrative']

'forwarded message date tue subject please investigate comenity bank retailer card scam sent hello name scammed comenity bank credit card provider company childrens place new york forever victoria secret original credit comenity bank lower limit began charge overage fee along late fee began pay close attention card find limit also changed well incurring overage late fee reached company comenity bank stated would change credit limit original limit reached told summit payment account corrected comenity bank credit card impacted credit score plummeted negative status im currently paying price due corruption affected detrimental way debt due company charging overage fee well late fee even initial credit limit fluctuating tremendously company charge major fee account willing correct account nervous said attorney reason im reaching im employee company ruining credit plz help name contact info thank'

EDA

In [79]:
df.shape

(124633, 2)

In [80]:
df['product'].value_counts()

product
credit_reporting       56283
debt_collection        21106
mortgages_and_loans    18758
credit_card            15023
retail_banking         13463
Name: count, dtype: int64

In [81]:
df['narrative'].str.len().describe()

count    124633.000000
mean        633.501079
std         832.494641
min          10.000000
25%         219.000000
50%         414.000000
75%         752.000000
max       20596.000000
Name: narrative, dtype: float64